# markdownlint-cli2 configuration (docs-heavy / low-churn profile)
# CLI runner: https://github.com/DavidAnson/markdownlint-cli2
# Rules:  https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#rules

config:
  default: false # disable all rules by default

  MD003:
    style: atx
  # MD003 — heading-style
  # Keep headings consistent: prefer ATX style (## Heading).

  MD009: true  # trailing spaces
  MD010: true  # hard tabs
  MD012: true  # multiple blank lines

  MD013:
    line_length: 160
    code_blocks: false
    tables: false
  # MD013 — line-length
  # Line-length is noisy in docs; enforce only outside docs (see overrides).
  # (If you want a global default anyway, set it here; override will disable in docs.)

  MD022: true  # heading spacing

  MD024:
    siblings_only: true
  # MD024 — no-duplicate-heading
  # Duplicate headings are usually confusing. siblings_only reduces false positives.

  MD025: true
  # MD025 — single-title
  # Only one H1 per document.

  MD029:
    style: one_or_ordered
  # MD029 — ordered-list-item-prefix
  # Ordered list numbering style is mostly preference; tolerant mode reduces noise.

  MD030: true  # list marker spacing

  MD033:
    allowed_elements:
      - br
      - details
      - summary
      - kbd
      - img
  # MD033 — no-inline-html
  # Allow a small set of practical HTML elements commonly used in docs.

  MD036: false
  # MD036 — no-emphasis-as-heading
  # Bold-as-heading is common in docs; disable to avoid churn.

  MD040: true
  # MD040 — fenced-code-language
  # Require language tags on fenced code blocks (```bash, ```yaml, etc.).
  # High-signal: improves readability + highlighting + tooling.

  MD041: true
  # MD041 — first-line-heading
  # File should start with an H1 heading.

  MD060:
    style: padded
  # MD060 — table-column-style
  # Keep table formatting consistent; padded matches common editor output.

overrides:
  # Docs: disable line-length entirely (prose, URLs, templates, history capsules).
  - files:
      - "docs/**"
    config:
      MD013: false

  # Templates: structure rules often intentionally violated.
  - files:
      - "docs/TEMPLATES/**"
    config:
      MD041: false
      MD025: false
