apiVersion: hee/v1
kind: Contract
metadata:
  name: pr-handoff-v1
  description: YAML-first contract for PR handling + handoffs + evidence capture
  labels:
    area: governance
    domain: pr-handoff
spec:
  authority:
    anchor:
      kind: soa
      path: $HOME/.hee
    chain:
    - soa
    - gcic
    - dric
    - shell
  rules:
    yaml_first:
      must: true
    non_yaml_first_gate:
      must: true
    ci_green_gate:
      must: true
    evidence_capture:
      must: true
    gh_issue_help:
      must: true
      definition: 'When creating/updating GH issues: search by run_id/url first; record
        issue pointer to OUTDIR/issue.pointer.kv; include fenced METs YAML in operational
        comments when applicable.'
    color_default_on:
      must: true
      definition: Color/pretty output MUST be default-on. Opt-out only via explicit
        modifier HEE_COLOR=0. Evidence flows that pipe to tee MUST set GH_FORCE_TTY=1,
        FORCE_COLOR=1, CLICOLOR_FORCE=1 or tool-specific always-color flags.
    color_helpers_present:
      must: true
      path: library/bash/hee_color.sh
  decisions:
    evidence_pointer_exts_allowed:
    - md
    - json
  artifacts:
    contract_yaml:
      path: pills/contracts/pr-handoff.v1.yaml
    handoff_yaml:
      required: true
      pattern: pills/handoff/handoff.pr<PRNUM>.v1.yaml
      required_fields:
      - pr_number
      - branch
      - head_sha
      - base
      - ci_status
      - evidence_outdir
