apiVersion: hee/v1
kind: ConvoStatus
metadata:
  generated_utc: "20260209T182720Z"
spec:
  what:
    - "WU status review"
    - "Branch/PR/Issue snapshot"
  how_to_check:
    - "gh pr list"
    - "gh issue list"
    - "git branch -a"
