apiVersion: hee/v1
kind: Contract
metadata:
  name: hee-kind-registry
  description: "Authoritative registry of HEE object kinds. Kind is tiny + stable. Case follows Kubernetes canon."
  labels:
    domain: hee
    scope: governance
    topic: kind-registry
    artifact: contract
  annotations:
    inuid: "698e3412-47e8-832f-ad2d-25fb3c63f0af"
    updated-at: "2026-02-12T20:42:56-06:00"

spec:
  invariants:
    - "Kind is tiny and stable."
    - "Registry is authoritative."
    - "Observed kinds do not automatically become active kinds."
    - "Kind case follows Kubernetes canon (PascalCase singular)."
    - "metadata.annotations.inuid is required for all HEE-object YAML."
    - "inuid may be null ONLY with a very good reason; reason must be recorded."

  active_kinds: ["Card","Pill","Delta","Contract","Blueprint","Plan"]

  plan_sub_structs_not_kinds: ["WU","Step","StepUnordered"]

  lint_policy:
    kind_case:
      current: "WARN"
      future: "ERROR"
      style: "nagios"
    inuid_null_reason:
      strict_schema: "schemas/hee/v1/hee-object.strict.schema.json"
      rule: "Strict mode requires inuid; if null then require inuid_null_reason."

  inuid_rules:
    required: true
    allow_null: true
    null_requires_reason: true
    allowed_null_reasons: ["bootstrap","test","fixture"]
